#! /usr/bin/env bash

fetch_content() {
    for name in "$@"
    do
        cat "${name}.content"
    done
}

format_blog_contents() {
    find . -name '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_blog.m4' -printf "%f %f\n" |
    sed -e 's/[\_][^\ ]*/ /1' |
    sort -nr |
    while read date filename
    do
        iso_date=$(date --date=${date} '+%Y-%m-%d')
        long_date=$(date --date=${date} '+%B %d, %Y')

        m4 \
            --prefix-builtins \
            -DISO_DATE="${iso_date}" \
            -DLONG_DATE="${long_date}" \
            < "${filename}" | sed -e 's/[\$]/__DOLLAR__/g' # Get around m4 interpretation of $[0-9] arguments
    done
}

m4 \
    --prefix-builtins \
    -DABOUT_CONTENTS="$(fetch_content about)" \
    -DLINK_CONTENTS="$(fetch_content links)" \
    -DCOMMENT_CONTENTS="$(fetch_content comments)" \
    -DBLOG_CONTENTS="$(format_blog_contents)" \
    < "index.m4" |
sed -e 's/__DOLLAR__/$/g'

